##############
#This file should be run in the third. 
#This file utilizes the 'gene.go.mat', 'hs.all.gene.go.mat', 'molecule.ensembl.id' and 'hs.ensembl.symbol.map' RData files generated by the 'molecule_go_map.R' file.
#Also this file utilizes the 'top.50.feature' RData file created by the 'molecule_classification.R' file.
#Also this file utilizes the molecules RData files stored in the 'additional_file' directory of the SPAGI2 repository.
#In a separate drectory, store the 'molecule_classification_model.R' file.
#And also create a folder name as 'object' in the current directory and store the RData files. But create a separate directory as 'molecule_object' and store here the molecules RData files.
#This R file contains the code for the random forest classification model for the pathway molecules GO matrix of the selected top 50 features.
#First we will build the classification model with only the top features of all the known molecules GO information and 
#Then we will predict all the other ensembl genes without the known molecules with the model.
#After that we will combine all the known pathway molecules with the model's predicted molecules.
#Also here we will convert the ensembl gene ids of the molecules to their gene symbols.
#Finally we will save all the receptors, kinases and the transcription factors in the 'result' subdirectory of the current directory to use in the next file "generate_pathway.R"
##############





#####
##Read the training Data
load("object/genes.go.mat.RData")
#it is very much required by random forest (data frame) - less error prone
train.data<-as.data.frame(genes.go.mat)
#making the col names legal - here ':' changed to '.' from the colnames part
names(train.data) <- make.names(names(train.data))
#making the type values as factor
train.data$type <- as.factor(train.data$type)
table(train.data$type)
#  1    2    3    4    5 
#680  636  440  997 2492 
##
#####




#####
##Read the test data
load("object/hs.all.gene.go.mat.RData")
#it is very much required by random forest (data frame) - less error prone
test.data<-as.data.frame(hs.all.gene.go.mat)
#making the col names legal - here ':' changed to '.' from the colnames part
names(test.data) <- make.names(names(test.data))
#making the type values as factor
test.data$type <- as.factor(test.data$type)
##
#####




#####
##Read the top 50 features-taken from previous result-"rf_classification_model_v1.R" file
load("object/top.50.feature.RData")
##
#####



#####
##get the train data with only the top 50 features
train.data.filtered<-train.data[,c("type",top.50.feature)]
dim(train.data.filtered)
#[1] 5245   51
##


##get the test data with only the top 50 features
test.data.filtered<-test.data[,c("type",top.50.feature)]
dim(test.data.filtered)
#[1] 19939   51
##


##load the molecules' (4 different types) ensembl IDs - taken from "molecule_go_map.R" file
load("object/molecule.ensembl.id.RData")
length(molecule.ensembl.id)
#[1] 2763
##


##Now get only the test data without the molecules data types 
test.data.filtered.clean<-test.data.filtered[(!(rownames(test.data.filtered) %in% molecule.ensembl.id)),]
dim(test.data.filtered.clean)
#[1] 17186    51
##




##################### Now build the model with the train data and classify the test data #######
##Random Forest
#install.packages("randomForest")
library(randomForest)
#

#Prediction & Confusion Matrix - train data
#install.packages("caret")
library(caret)   ##this is for confusionMatrix()
#
##


############
##Now build the model and predict the test data
rf.selected <- randomForest(type~., data=train.data.filtered)
rf.selected$confusion
##


##Prediction & Confusion Matrix - train data
p1.selected <- predict(rf.selected, train.data.filtered)
confusionMatrix(p1.selected, train.data.filtered$type)
##


##
#Prediction & Confusion Matrix - test data - 
#here at the same time we will take the molecule type from the model 
#p2.selected <- predict(rf.selected, test.data.filtered.clean)
#confusionMatrix(p2.selected, test.data.filtered.clean$type)
##to get individual classification type result for each gene
p2.selected <- data.frame(predict(rf.selected, test.data.filtered.clean))
colnames(p2.selected)<-"model_type"
dim(p2.selected)
#[1] 17186     1
#combine the model result with the test data
#p2.selected.result<-cbind(p2.selected, test.data.filtered.clean)
#p2.selected.result[1:4,1:4]
##
#############






##################
#####Now convert the ensembl gene ids to gene symbols from the model result and
#####then take the type result as 1,2,3,4 for molecules and 
#####then combine these results with the original LG, RP, KN, TF molecules

##load the human ensembl symbol map data table - "hs.ensembl.symbol.map.RData" - taken from "mol_go_map_v1.R" file
load("object/hs.ensembl.symbol.map.RData")
##


##Now convert the ensembl gene ids to gene symbols from the model result
#first convert the symbol map table with the same sequence as the model result ensembl gene ids
hs.ensembl.symbol.map.filtered<-hs.ensembl.symbol.map[match(rownames(p2.selected), hs.ensembl.symbol.map$ensembl_gene_id),]
dim(hs.ensembl.symbol.map.filtered)
#[1] 17186     2
#now change the rownames of the model result by the filtered symbol map table's external gene name
rownames(p2.selected)<-hs.ensembl.symbol.map.filtered$external_gene_name
##


##Now take the individual molecule type result from the model
model.LG<-rownames(p2.selected)[which(p2.selected$model_type==1)]
model.RP<-rownames(p2.selected)[which(p2.selected$model_type==2)]
model.KN<-rownames(p2.selected)[which(p2.selected$model_type==3)]
model.TF<-rownames(p2.selected)[which(p2.selected$model_type==4)]
##


##Load the original LG, RP, KN and TF molecules
load("molecule_object/LG.gene.list.RData")
load("molecule_object/RP.gene.list.RData")
load("molecule_object/KN.gene.list.RData")
load("molecule_object/TF.gene.list.RData")
##


##Combine the molecules of original and model result of each type
lg.molecule.all<-unique(c(LG.gene.list, model.LG))
rp.molecule.all<-unique(c(RP.gene.list, model.RP))
kn.molecule.all<-unique(c(KN.gene.list, model.KN))
tf.molecule.all<-unique(c(TF.gene.list, model.TF))
##


##Remove the duplicate types by attaining only the first type, 
##to overcome the infinite loop by SPAGI during pathway path data building
##here, we will consider only the RP, KN and TF molecules, as these are only used by SPAGI
##RP molecule will be as it is, KN will be the unique without the RP ones, TF will be without the RP and KN
#now get the individual clean molecule types
rp.molecule.all.clean<-rp.molecule.all
kn.molecule.all.clean<-kn.molecule.all[!(kn.molecule.all %in% rp.molecule.all.clean)]
tf.molecule.all.clean<-tf.molecule.all[!(tf.molecule.all %in% rp.molecule.all.clean |
                                           tf.molecule.all %in% kn.molecule.all.clean)]
##


##Now save the clean molecule type to be used by the SPAGI to build the pathway path data
#save(rp.molecule.all.clean, file="result/rp.molecule.all.clean.RData")
#save(kn.molecule.all.clean, file="result/kn.molecule.all.clean.RData")
#save(tf.molecule.all.clean, file="result/tf.molecule.all.clean.RData")
##
##################



