#' Pathway path data
#'
#' Pathway path used as background data, generated using STRINGdb PPI.
#'
#' @docType data
#'
#' @usage data(pathway.path.new)
#'
#' @format An object of list containing pathway paths that is used as background data.
#'
#' @keywords datasets
#'
#' @examples
#' head(summary(pathway.path.new)
"pathway.path.new"


#' Data from mouse embryonic dental epithelium cell at E13.5,
#' contains transcriptomic profiles microarray data of mouse tooth epithelium cell at embryonic day E13.5.
#' The cell has 3 biological replicates.
#'
#' @docType data
#'
#' @usage data(tooth.epi.E13.5)
#'
#' @format An object of matrix containing in normalized and log2 format gene expression value of mouse tooth epithelium cell.
#'
#' @keywords datasets
#'
#' @references Daniel J O'Connell et al, Science Signaling, 2012 Jan 10;5(206):ra4.
#' (\href{https://pubmed.ncbi.nlm.nih.gov/22234613/}{PubMed})
#'
#' @examples
#' head(tooth.epi.E13.5)
"tooth.epi.E13.5"


#' Receptor proteins that are generally highly expressed in many cells / tissues
#' Generated by utilizing human and mouse encode data sets from the "pathway_cleaning.R" additional file
#' Used as background data
#'
#' @docType data
#'
#' @usage data(rp.median.exp.4)
#'
#' @format An object of matrix containing in normalized and log2 format gene expression value of mouse tooth epithelium cell.
#'
#' @keywords datasets
#'
#' @references The ENCODE Project Consortium, Nature 2012 Sep 6;489(7414):57-74
#' (\href{https://www.ncbi.nlm.nih.gov/pubmed/22955616}{PubMed})
#' @references The Mouse ENCODE Consortium, Genome Biology 2012 Aug 13;13(8):418
#' (\href{https://pubmed.ncbi.nlm.nih.gov/22889292/}{PubMed})
#'
#' @examples
#' head(rp.median.exp.4)
"rp.median.exp.4"

